version: '3'
services:
  #  собираем контенер
  #  вначале ставим postgres из dockerhub
  postgres:
    restart: always
    image: 'postgres:15'
    container_name: 'bicycles-postgres'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'  #TODO подумать о защите данных
      - 'POSTGRES_DB=bicycles'
    ports:
      - '5432:5432'