version: '3'
services:
  #  собираем контенер
  #  вначале ставим postgres из dockerhub
  postgres:
    restart: always
    image: 'postgres:15'
    container_name: 'bicycles-postgres'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '5432:5432'